[package]
name = "traits"
version = "0.1.0"
authors = ["Tanya L. Crenshaw <tcrenshaw@fastly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "1"