[package]
name = "ffi"
version = "0.1.0"
authors = ["Tanya L. Crenshaw <tcrenshaw@fastly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"

[build-dependencies]
metadeps = "1.1.2"