[package]
name = "aoc"
version = "0.1.0"
authors = ["tcrenshaw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1"
