[package]
name = "rwlock"
version = "0.1.0"
authors = ["Tanya L. Crenshaw <tcrenshaw@fastly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
rand = "0.7.3"