[package]
name = "day4"
version = "0.1.0"
authors = ["Tanya L. Crenshaw <tcrenshaw@fastly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

md5 = "0.7.0"